      Subroutine Type1996

! Object: ProcEDE_horizontal_tank
! Simulation Studio Model: ProcEDE_horizontal_tank
! 

! Author: DRAOU MOHICNE
! Editor: 
! Date:	 October 27, 2024
! last modified: October 27, 2024
! 
! 
! *** 
! *** Model Parameters 
! *** 
!			Tank Volume	m^3 [-Inf;+Inf]
!			Tank Length	m [-Inf;+Inf]
!			Tank Diameter	m [-Inf;+Inf]
!			Insulation Thickness	m [-Inf;+Inf]
!			Insulation Conductivity	W/m.K [-Inf;+Inf]
!			Thermostat Setpoint	C [-Inf;+Inf]
!			Thermostat Deadband	deltaC [-Inf;+Inf]
!			Element Height	m [-Inf;+Inf]
!			Fluid Specific Heat	J/kg.K [-Inf;+Inf]
!			Fluid Density	kg/m^3 [-Inf;+Inf]

! *** 
! *** Model Inputs 
! *** 
!			Element Power	W [-Inf;+Inf]
!			Inlet Temperature	C [-Inf;+Inf]
!			Inlet Flow Rate	kg/hr [-Inf;+Inf]
!			Ambient Temperature	C [-Inf;+Inf]

! *** 
! *** Model Outputs 
! *** 
!			Outlet Temperature	C [-Inf;+Inf]
!			Tank Temperature	C [-Inf;+Inf]
!			Element Power Output	W [-Inf;+Inf]
!			Heat Loss	W [-Inf;+Inf]

! *** 
! *** Model Derivatives 
! *** 
!			Tank Temperature	C [-Inf;+Inf]

! (Comments and routine interface generated by TRNSYS Simulation Studio)
!************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


      Use TrnsysConstants
      Use TrnsysFunctions

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type1996

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
      Implicit None

      Double Precision Timestep,Time
      Integer CurrentUnit,CurrentType


!    PARAMETERS
      DOUBLE PRECISION Tank_Volume
      DOUBLE PRECISION Tank_Length
      DOUBLE PRECISION Tank_Diameter
      DOUBLE PRECISION Insulation_Thickness
      DOUBLE PRECISION Insulation_Conductivity
      DOUBLE PRECISION Thermostat_Setpoint
      DOUBLE PRECISION Thermostat_Deadband
      DOUBLE PRECISION Element_Height
      DOUBLE PRECISION Fluid_Specific_Heat
      DOUBLE PRECISION Fluid_Density

!    INPUTS
      DOUBLE PRECISION Element_Power
      DOUBLE PRECISION Inlet_Temperature
      DOUBLE PRECISION Inlet_Flow_Rate
      DOUBLE PRECISION Ambient_Temperature

!    Local Variables
      DOUBLE PRECISION Tank_Area           ! Total tank surface area [m²]
      DOUBLE PRECISION UA_tank            ! Overall heat transfer coefficient [W/K]
      DOUBLE PRECISION Element_State      ! Heating element state (0 or 1)
      DOUBLE PRECISION Q_element          ! Heat input from element [W]
      DOUBLE PRECISION Q_flow            ! Heat transfer from flow [W]
      DOUBLE PRECISION Q_loss            ! Heat loss to environment [W]
      DOUBLE PRECISION Tank_Temp         ! Current tank temperature [C]
      DOUBLE PRECISION Tank_Temp_New     ! New tank temperature [C]
      DOUBLE PRECISION dTankTemp_dt      ! Rate of change of tank temperature [C/hr]
      DOUBLE PRECISION denominator       ! For safe division
      DOUBLE PRECISION PI                ! Pi constant
      PARAMETER (PI = 3.141592653589793d0)

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Get the Global Trnsys Simulation Variables
      Time=getSimulationTime()
      Timestep=getSimulationTimeStep()
      CurrentUnit = getCurrentUnit()
      CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Version Number for This Type
      If(getIsVersionSigningTime()) Then
		Call SetTypeVersion(17)
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do Any Last Call Manipulations Here
      If(getIsLastCallofSimulation()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
      If(getIsEndOfTimestep()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the "Very First Call of the Simulation Manipulations" Here
      If(getIsFirstCallofSimulation()) Then

		!Tell the TRNSYS Engine How This Type Works
		Call SetNumberofParameters(10)           !The number of parameters that the the model wants
		Call SetNumberofInputs(4)                   !The number of inputs that the the model wants
		Call SetNumberofDerivatives(1)         !The number of derivatives that the the model wants
		Call SetNumberofOutputs(4)                 !The number of outputs that the the model produces
		Call SetIterationMode(1)                             !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
		Call SetNumberStoredVariables(0,0)                   !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
		Call SetNumberofDiscreteControls(0)               !The number of discrete control functions set by this model (a value greater than zero requires the user to use Solver 1: Powell's method)

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
      If (getIsStartTime()) Then
      Tank_Volume = getParameterValue(1)
      Tank_Length = getParameterValue(2)
      Tank_Diameter = getParameterValue(3)
      Insulation_Thickness = getParameterValue(4)
      Insulation_Conductivity = getParameterValue(5)
      Thermostat_Setpoint = getParameterValue(6)
      Thermostat_Deadband = getParameterValue(7)
      Element_Height = getParameterValue(8)
      Fluid_Specific_Heat = getParameterValue(9)
      Fluid_Density = getParameterValue(10)


      Element_Power = GetInputValue(1)
      Inlet_Temperature = GetInputValue(2)
      Inlet_Flow_Rate = GetInputValue(3)
      Ambient_Temperature = GetInputValue(4)

	
   !Check the Parameters for Problems (#,ErrorType,Text)
   !Sample Code: If( PAR1 <= 0.) Call FoundBadParameter(1,'Fatal','The first parameter provided to this model is not acceptable.')

   !Set the Initial Values of the Outputs (#,Value)
		Call SetOutputValue(1, 0.d0) ! Outlet Temperature
		Call SetOutputValue(2, 0.d0) ! Tank Temperature
		Call SetOutputValue(3, 0.d0) ! Element Power Output
		Call SetOutputValue(4, 0.d0) ! Heat Loss


   !If Needed, Set the Initial Values of the Static Storage Variables (#,Value)
   !Sample Code: SetStaticArrayValue(1,0.d0)

   !If Needed, Set the Initial Values of the Dynamic Storage Variables (#,Value)
   !Sample Code: Call SetDynamicArrayValueThisIteration(1,20.d0)

   !If Needed, Set the Initial Values of the Discrete Controllers (#,Value)
   !Sample Code for Controller 1 Set to Off: Call SetDesiredDiscreteControlState(1,0) 

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!ReRead the Parameters if Another Unit of This Type Has Been Called Last
      If(getIsReReadParameters()) Then
		!Read in the Values of the Parameters from the Input File
      Tank_Volume = getParameterValue(1)
      Tank_Length = getParameterValue(2)
      Tank_Diameter = getParameterValue(3)
      Insulation_Thickness = getParameterValue(4)
      Insulation_Conductivity = getParameterValue(5)
      Thermostat_Setpoint = getParameterValue(6)
      Thermostat_Deadband = getParameterValue(7)
      Element_Height = getParameterValue(8)
      Fluid_Specific_Heat = getParameterValue(9)
      Fluid_Density = getParameterValue(10)

		
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!Read the Inputs
      Element_Power = GetInputValue(1)
      Inlet_Temperature = GetInputValue(2)
      Inlet_Flow_Rate = GetInputValue(3)
      Ambient_Temperature = GetInputValue(4)
		

	!Check the Inputs for Problems (#,ErrorType,Text)
	!Sample Code: If( IN1 <= 0.) Call FoundBadInput(1,'Fatal','The first input provided to this model is not acceptable.')
 
      If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------

! Get current tank temperature from numerical solution
Tank_Temp = getNumericalSolution(1)

! Input validation
IF (Tank_Volume <= 0.0d0) THEN
    Call FoundBadParameter(1,'Fatal','Tank volume must be greater than zero')
    RETURN
END IF

IF (Tank_Diameter <= 0.0d0) THEN
    Call FoundBadParameter(3,'Fatal','Tank diameter must be greater than zero')
    RETURN
END IF

IF (Fluid_Density <= 0.0d0) THEN
    Call FoundBadParameter(10,'Fatal','Fluid density must be greater than zero')
    RETURN
END IF

IF (Fluid_Specific_Heat <= 0.0d0) THEN
    Call FoundBadParameter(9,'Fatal','Specific heat must be greater than zero')
    RETURN
END IF

! Initialize Element_State if it's the first call
IF (getIsStartTime()) THEN
    Element_State = 0.0d0
END IF

! Calculate tank surface area (with safety checks)
Tank_Area = PI * Tank_Diameter * Tank_Length + 2.0d0 * (PI * (Tank_Diameter/2.0d0)**2)

! Calculate overall heat transfer coefficient with safety checks
IF (Tank_Diameter > 0.0d0 .AND. Insulation_Thickness > 0.0d0) THEN
    UA_tank = (2.0d0 * PI * Tank_Length * Insulation_Conductivity) / &
              LOG((Tank_Diameter/2.0d0 + Insulation_Thickness)/(Tank_Diameter/2.0d0)) + &
              2.0d0 * PI * (Tank_Diameter/2.0d0)**2 * Insulation_Conductivity / &
              MAX(Insulation_Thickness, 1.0d-10)  ! Prevent division by zero
ELSE
    UA_tank = 0.0d0
END IF

! Thermostat control logic with hysteresis
IF (Tank_Temp < (Thermostat_Setpoint - Thermostat_Deadband/2.0d0)) THEN
    Element_State = 1.0d0
ELSE IF (Tank_Temp > (Thermostat_Setpoint + Thermostat_Deadband/2.0d0)) THEN
    Element_State = 0.0d0
END IF

! Calculate heat flows with safety checks
Q_element = Element_State * MAX(Element_Power, 0.0d0)  ! Ensure non-negative power

! Safe calculation of flow heat transfer
IF (ABS(Inlet_Flow_Rate) < 1.0d-10) THEN
    Q_flow = 0.0d0
ELSE
    Q_flow = Inlet_Flow_Rate * Fluid_Specific_Heat * &
             (Inlet_Temperature - Tank_Temp) / 3600.0d0
END IF

! Heat loss calculation
Q_loss = UA_tank * (Tank_Temp - Ambient_Temperature)

! Safe calculation of temperature derivative
denominator = Tank_Volume * Fluid_Density * Fluid_Specific_Heat
IF (ABS(denominator) < 1.0d-10) THEN
    dTankTemp_dt = 0.0d0
ELSE
    dTankTemp_dt = (Q_element + Q_flow - Q_loss) / denominator * 3600.0d0
END IF

! Limit the rate of change to prevent numerical instabilities
dTankTemp_dt = MAX(MIN(dTankTemp_dt, 100.0d0), -100.0d0)

! Set the derivative for TRNSYS solver
Call SetNumericalDerivative(1, dTankTemp_dt)

! Set outputs
Call SetOutputValue(1, Tank_Temp)             ! Outlet Temperature = Tank Temperature (well-mixed)
Call SetOutputValue(2, Tank_Temp)             ! Tank Temperature
Call SetOutputValue(3, Q_element)             ! Element Power Output [W]
Call SetOutputValue(4, Q_loss)                ! Heat Loss [W] 

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Outputs from this Model (#,Value)
		Call SetOutputValue(1, 0.d0) ! Outlet Temperature
		Call SetOutputValue(2, 0.d0) ! Tank Temperature
		Call SetOutputValue(3, 0.d0) ! Element Power Output
		Call SetOutputValue(4, 0.d0) ! Heat Loss

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Desired Disceret Control Signal Values for this Iteration (#,State)
!Sample Code:  Call SetDesiredDiscreteControlState(1,1)
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Final value of the Dynamic Variables in the Global Storage Array (#,Value)
!Sample Code:  Call SetDynamicArrayValueThisIteration(1,T_FINAL_1)
!-----------------------------------------------------------------------------------------------------------------------
 
      Return
      End
!-----------------------------------------------------------------------------------------------------------------------

